"""initial migration

Revision ID: 2afea9e9adc
Revises: None
Create Date: 2016-08-29 10:50:34.525815

"""

# revision identifiers, used by Alembic.
revision = '2afea9e9adc'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
