"""empty message

Revision ID: f8e9001a4e67
Revises: 297ed21f8874
Create Date: 2016-09-02 02:29:35.413418

"""

# revision identifiers, used by Alembic.
revision = 'f8e9001a4e67'
down_revision = '297ed21f8874'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
